kitspace/kitspace

src/store_buttons.scss

add css maintain equal space usage of purchase buttons in mobile

---

src/page.scss

add css increase line-height of page title to prevent text overlap

---

src/board_showcase.jsx

add lazy loading to the board showcase images

---

src/board_showcase.jsx

Adds synchronised image fade in on board pages to support lazy load #52

Fixes #52 

---

boards.txt

tried to add our project 8BitMixTape Nextlevel edition. Not very experienced with the workflow. Hope it works. Best, Urs

added project 8BitMixtape

---

README.md

Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>

fix yaml validator link

---

boards.txt

I've had a go at this. The 1-click-bom file generated cleanly, but I'm interested to see what happens with the piezo component, as my normal supplier is not one of the supported ones.

Added piezo sensor project

---

boards.txt

hei kaspar,
adding this now. but still a bit confused how to use it.
it didnt find the bom, somehow.
ttyl
m

Add 8BitmixtapeNEO_ShenzhenReady

---

boards.txt
configure

Excited to make it easier for people to build my widget!

Add Sympetrum-v2 electronic conference badge

---

boards.txt
src/index/board_card.jsx

Get rid of JS truncation of text

---

boards.txt

Please add ULX3S FPGA R&D board

ULX3S FPGA

---

boards.txt

hi kaspar,
ich mach die nächsten tage noch ein paar boards ufe.
m

Add GOSH-Board_UGM

---

boards.txt

See https://community.libre.space/t/2m-70cm-diplexer/2370/17 for project details

Added the SatNOGS Diplexer

---

boards.txt

Added https://github.com/Jan--Henrik/CH330_Hardware

Added CH330 HW

---

boards.txt

hi kaspar,
hier noch das neue WiFi enabled mixtape

Add ESPTINY86 

---

boards.txt

Added our plant moisture to sound and light sensor.

Add singingplants

---

boards.txt

I added the `kitspace.yml` file and `bom.tsv` to my repo but kitspace seems to have trouble with my `README.md` file.

Add darling to project list

---

src/install_extension.jsx

Fix chrome extension link

---

boards.txt

This should add Sangaboard v3 to Kitspace

Add Sangaboard v3

---

boards.txt

Added https://github.com/Jan--Henrik/OtterScreenAdapter/tree/master

Add OtterScreenAdapter

---

boards.txt

Add OtterPill

---

configure
tasks/page/processBOM.js
tasks/page/processGerbers.js

Make the build system handle spaces in folder names.

Allow spaces in folders

---

boards.txt

Added USB-LED-Otter

---

README.md
boards.txt
configure
tasks/page/makePage.js
tasks/page/makeReadme.js
tasks/page/processBOM.js
tasks/page/processGerbers.js

Added the ability to define a `readme` path in the Kitspace yaml. 
Also did some clean up of the repetitive multi repo checking by moving that logic further up the build process.

Add yaml readme path field

---

boards.txt

this covers 2 assembly variants for the same set of PCB layout files: 
1 gerbers folder, 2 BOMs, 2 readmes

Adding DIY Particle Detector as multi project

---

src/page/board_showcase.jsx
src/page/board_showcase.scss
src/page/page.jsx

Trace space link

---

src/_redirects

for my updated multi project's new ids without spaces, I hope the quotation marks are correct in order to preserve the spaces.
fixes #230 for now

adding two redirects

---

tasks/page/processGerbers.js

Fix color not being applied to multi projects

---

boards.txt

Add the fast diode board

---

boards.txt

Add aleksas/interferometer 

---

boards.txt

Add Glasgow

---

boards.txt

Add pyr0piezo

---

tasks/page/processGerbers.js

Will fix this properly in branch: fix-kicad-plotting, once legacy
projects are updated.

Work around kicad plotting issue

---

src/buy_parts/buy_parts.jsx
src/buy_parts/buy_parts.scss

Showing only the total number of parts can be confusing. To verify that parts were correctly added to cart the most useful thing to see are the number of lines that are supposed to be added. This fixes that.

Show lines in buy parts

---

boards.txt

Add Open Book

---

src/common.scss
src/title_bar.jsx
src/title_bar.scss

I had improved this on [kitspace-using-gitea](https://github.com/kitspace-using-gitea) so I am pulling these changes in. This was the incentive for #277 since I had used `React.Fragment` in this re-design. Previewed on: http://improve-title-bar-on-mobile.preview.kitspace.org/
Before:
---
---
After:
---
---
---

Improve title bar on mobile

---

.travis.yml
tasks/page/processBOM.js
tasks/page/processIBOM.js
tasks/page/run_ibom
tasks/utils/utils.js

What it says in the title. Done in a very simple way using KiCad's EAGLE board file importer, but it seems to work.
Before merging, we should probably have a systematic look through the existing projects to see if there are any that just don't work. You can see the results on http://eagle-ibom.preview.kitspace.org/

Add interactive HTML BOM pages for EAGLE projects

---

tasks/page/processBOM.js
tasks/page/processIBOM.js
tasks/page/run_ibom
tasks/utils/utils.js

Squashed the commits from #300 and made a new branch to test out the deploy.

Eagle IBOM retry

---

boards.txt

Add astrohat project

---

package.json
src/gerber_files.js
tasks/page/processGerbers.js
yarn.lock

Upgrade tracespace libs to ^4.2

---

dev_registry.json
src/1-click-bom/1-click-bom.html
src/buy_parts/buy_parts.jsx
src/index/index.html
src/index/index.jsx
src/install_extension.jsx
src/interactive_bom/interactive_bom.html
src/newsletter/newsletter.html
src/page/order_pcbs.jsx
src/page/page.html
src/page/page.jsx
src/submit/submit.html

Track clicks for PCB orders and buying parts

---

boards.txt

Add boards from the beehive project

Add boards from the beehive project

---

boards.txt

Add GPSMux board

---

boards.txt

https://github.com/Tyler-Ward/stacklight-hardware/pull/9

Add Tyler-Ward/stacklight-hardware

---

boards.txt

https://github.com/gregdavill/d20-hardware/pull/2

Add gregdavill/d20-hardware

---

boards.txt

https://github.com/hutscape/oak/pull/21

Add hutscape/oak

---

boards.txt

https://github.com/dhairyashah1/USBee32-S2/pull/11

Add dhairyashah1/USBee32-S2

---

boards.txt

Please add my modified version of inline filament diameter electronic circuitry to the kitspace list Thanks in advance.

Add modified infidel-sensor

---

boards.txt

https://github.com/bru4bas/gelatino-board/pull/1

Add bru4bas/gelatino-board

---

boards.txt

https://github.com/vektorious/test_tube_photometer/pull/2#event-5037783122

Add test_tube_photometer

---

boards.txt

https://github.com/Ottercast/OtterCastAmp/pull/2

Add OtterCastAmp

---

boards.txt

https://github.com/Ottercast/OtterCastAudioV2/pull/8

Add OtterCastAudioV2

---

boards.txt

https://github.com/LibreSolar/mppt-1210-hus/pull/1

Add LibreSolar/mppt-1210-hus

---

boards.txt

Add LouisLab/pivr

---

boards.txt

Add [DropBot](https://github.com/sci-bots/dropbot-v3) boards.

Add dropbot-boards

---

boards.txt

https://github.com/SdtElectronics/Xassette-Asterisk/pull/4#event-5670164418

Add Xassette-Asterisk

---

boards.txt

Add pyphotometry board

---

boards.txt

Hi, I am helping balthazar team on some projects, and I think the would be great fit on kitspace.

Adding balthazar-space keyboard

---

boards.txt

Add Open-Gamma-Project/SiPM-Carrier-Board

---

boards.txt

Add rosmo.io boards

---

boards.txt

Add AFBR-SiPM-Carrier-Board

---

boards.txt

Add Open-Gamma-Project/Mini-SiD

---

boards.txt

Added my newest PCB: https://github.com/OpenGammaProject/MicroFC-SiPM-Array-Board

Add MicroFC-SiPM-Array-Board

---

boards.txt

Hey there,
thanks for the great service. I've got another project for you, cheers!

Add Tiny-MicroFC-Carrier-Board
